
#Chat Restrictions
#talkRange doesn't have a toggle value, because then the mod would be useless
[restrictions]
	#Set to true to treat operators like players. Aka talking hits the entire world
	#Default: false
	opAsPlayer = false
	#The maximum range at which a player local to another player can be heard without requiring being an op.
	#Default: 100
	#Range: > 0
	talkRange = 100

#Miscellaneous
[miscellaneous]
	#Should the distance away be indicated in the chat? This also disables the custom prefix.
	rangeNotifier = true
	#Enable to use the prefix you defined to take place of range notification.
	usePrefix = false
	#If alternate prefix is enabled then the distance won't be displayed but this prefix will.
	prefix = ""

#These codes control the output of the colors sent to the client for the various parts of the mod
#Color codes reference at http://minecraft.wikia.com/wiki/Formatting_Codes
[color_codes]
	#The color to use when an error is issued
	errorColor = "§4"
	#The color to use for the usage text
	usageColor = "§2"
	#Sets the color the body of the message
	bodyColor = "§f"
	#The color to use when no other color will do
	defaultColor = "§f"
	#Sets the color for brackets []
	bracketColor = "§6"
	#Sets the color for angle braces <>
	angleBraceColor = "§7"
	#Sets the color to be used player names
	nameColor = "§f"
	#Sets the color for positional information
	posColor = "§e"
	#The color to use for channel names
	channelColor = "§2"

