
["QuiverHUD Settings"]
	#The margin on the left of the HUD Quiver.
	#Range: 16 ~ 1000
	HORIZONTAL_OFFSET = 16
	#Hide the HUD Quiver when not selecting a shootable item.
	HIDE = true
	#Animate the HUD Quiver showing and hiding.
	ANIMATE = true
	#Use the old model?
	OLD_MODEL = false
	#The margin on the top of the HUD Quiver.
	#Range: 16 ~ 1000
	VERTICAL_OFFSET = 16

