#
###Version, do not change!##
#Range: > 0
Version = 3

#Recruits Config:
[Recruits]
	#
	#----Should Recruits Name Tag Render for the owner----
	#	(takes effect after restart)
	#	default: true
	RenderNameTagforOwner = true
	#
	#Max XP a Recruit needs to Level Up
	#	(takes effect after restart)
	#	default: 200
	#Range: 50 ~ 10000
	RecruitsMaxXpForLevelUp = 200
	#
	#Max Recruits in a Village Chunk to Spawn
	#	(takes effect after restart)
	#	default: 1
	#Range: 1 ~ 10
	MaxSpawnRecruitsInVillage = 1
	#
	#----Should Pillagers attack all Living----
	#	(takes effect after restart)
	#	default: true
	ShouldPillagersRaidNaturally = true
	#
	#----Should Recruits Make Villager Huh? sound?----
	#	(takes effect after restart)
	#	default: true
	PlayVillagerAmbientSound = true
	#
	#----Should Recruits instead of Iron Golems spawn in Villages ----
	#	(takes effect after restart)
	#	default: true
	OverrideIronGolemSpawn = true
	#
	#----Should Pillagers attack Monsters----
	#	(takes effect after restart)
	#	default: true
	PillagerAttackMonsters = true
	#
	#----Should Monsters attack Pillagers----
	#	(takes effect after restart)
	#	default: true
	MonstersAttackPillagers = true
	#
	#----Should Pillagers do Friendlyfire ----
	#	(takes effect after restart)
	#	default: false
	PillagerFriendlyFire = false
	#
	#----Should Pillagers Spawn naturally ----
	#	(takes effect after restart)
	#	default: true
	PillagerSpawn = true

