
#Server Settings
[Server]
	#If 'true', Atlases will be able to store Empty Maps and auto-fill them as you explore.
	"Enable Empty Map Entry and Fill" = true
	#The maximum number of Maps (Filled & Empty combined) allowed to be inside an Atlas.
	#Range: > 1
	"Max Map Count" = 128
	#Scale the mini-map to a given pixel size. (Default is 64)
	#Range: > 1
	"Force Minimap Scaling" = 64
	#If 'true', Atlases will require to be held in Main or Off Hands to be displayed or updated.
	"Force Use In Hands" = false
	#If 'true', the Mini-Map of the Active Map will be drawn on the HUD while the Atlas is on your hot-bar or off-hand.
	"Draw Minimap HUD" = true

